version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ../Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - API_ENV=production
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
